### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#1]
- [ ] Configure index
- [ ] Implement search results

Example: https://www.bevespi.com/search-results.html?q=copd&searchIn=%2Fcontent%2FWebsiteServices%2Fus%2F417-bevespi-consumer-rwd%2Fen%2Fus&_charset_=UTF-8

**Comment by paolomoz** [comment]
@jelmini looks like the search form is part of the header, so maybe we can keep it there. This issue would be about implementing the search-results page based on the 'q' parameter; WDYT?

**Comment by jelmini** [comment]
Agreed. However, there is a search field in the search-results page as well, which I think I can still implement in the context of this task.
