### ISSUE TITLE
Search: identify reason for different results franklin/www

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#195]
example below: franklin has less results (for 'bevespi')

- https://www.bevespi.com/search-results.html?q=bevespi&start=20&searchIn=/content/WebsiteServices/us/417-bevespi-consumer-rwd/en/us:
- https://franklin.bevespi.com/search-results?q=bevespi&p=1

**Comment by jelmini** [comment]
Indexing is not selecting all relevant content for some pages. For example, for this page https://franklin.bevespi.com/copd-management-resources/activities-with-copd the only content present in [query-index.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BCB9EE406-795A-49F8-8B2A-5BF07085CE51%7D&file=query-index.xlsx&action=default&mobileredirect=true) is:

> LIVING WITH COPDTips to stay motivated
> 5 things to do with your kids or grandkids

This [expression in helix-query.yaml](https://github.com/hlxsites/bevespi/blob/main/helix-query.yaml#L20-L22) should be improved to index all relevant page content.
