### ISSUE TITLE
PDF files: move all PDFs and set redirects

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#251]
e.g. here https://main--bevespi--hlxsites.hlx.page/copd-management-resources

<img width="1113" alt="Screenshot 2023-11-02 at 10 57 10" src="https://github.com/hlxsites/bevespi/assets/111385/e6a3f339-376f-4266-86a0-3bbce608874b">

**Comment by lansami** [comment]
added pdfs 
https://main--bevespi--hlxsites.hlx.page/docs/breatheinout-ebook.pdf
https://main--bevespi--hlxsites.hlx.page/docs/3311503-bevespi-consumer-how-to-use-tearsheet.pdf

**Comment by lansami** [comment]
https://main--bevespi--hlxsites.hlx.page/docs/bevespi-pi-central-digital-prescribing-information.pdf

**Comment by dicagno** [comment]
> https://main--bevespi--hlxsites.hlx.page/docs/bevespi-pi-central-digital-prescribing-information.pdf

Shouldn't this link stay external?

**Comment by lansami** [comment]
yes, I think it should, I've removed the usage of this pdf, but forgot to update the issue
