### ISSUE TITLE
Tile from hero is not centred on some pages

### ISSUE THREAD

**Issue by lansami** [hlxsites/bevespi#289]
https://franklin.bevespi.com/how-to-use-bevespi-inhaler
<img width="273" alt="image" src="https://github.com/hlxsites/bevespi/assets/26941572/941ed2c8-c429-45a8-82e9-17cb44790541">

https://franklin.bevespi.com/bevespi-side-effects
<img width="264" alt="image" src="https://github.com/hlxsites/bevespi/assets/26941572/66c5b13d-54c0-4cda-bc0b-cc800e091d4a">

https://franklin.bevespi.com/copd-management-resources/talking-to-your-doctor
<img width="291" alt="image" src="https://github.com/hlxsites/bevespi/assets/26941572/ee7792eb-9c5c-4999-b6c0-81a7f37ec03d">

https://franklin.bevespi.com/contact-us
<img width="265" alt="image" src="https://github.com/hlxsites/bevespi/assets/26941572/162408f1-d409-4f8b-bf6a-9adb30438a0e">

**Comment by paolomoz** [comment]
@dicagno this was done thid morning as a quick fix (QA scope) https://github.com/hlxsites/bevespi/pull/287
