### ISSUE TITLE
CLS is consistently 0.017

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#29]
example: https://pagespeed.web.dev/analysis/https-issue-11-hero-continued--bevespi--hlxsites-hlx-page-copd-treatment/d4km4g3s2q?form_factor=mobile

**Comment by paolomoz** [comment]
@dicagno the main contributor to CLS is the middle part of the header. See the shift below which is reproduceable with a slow 3g network setup in the browser.

<img width="1792" alt="Screenshot 2023-10-12 at 08 58 45" src="https://github.com/hlxsites/bevespi/assets/111385/46ca80bf-7349-47f4-9aae-bf02b2d445dd">
<img width="1792" alt="Screenshot 2023-10-12 at 08 58 48" src="https://github.com/hlxsites/bevespi/assets/111385/6d7a7ed3-53e0-49e2-95d8-dc538dd80484">

**Comment by dicagno** [comment]
Setting low prio since this requires new evaluation and more investigation as we add more "features", and for now it looks good (and cannot be realistically scaled down to 0).
