### ISSUE TITLE
Issues with search result style

### ISSUE THREAD

**Issue by lansami** [hlxsites/bevespi#290]
Title from hero should be vertically centred
Shape design should be there
Space should be less on results

https://franklin.bevespi.com/search-results?q=bevespi&p=1
<img width="433" alt="image" src="https://github.com/hlxsites/bevespi/assets/26941572/e171f916-f6b4-4c44-a051-80955c6c89ee">

https://www.bevespi.com/search-results.html?q=&searchIn=%2Fcontent%2FWebsiteServices%2Fus%2F417-bevespi-consumer-rwd%2Fen%2Fus&_charset_=UTF-8

**Comment by paolomoz** [comment]
@lansami this was done this morning as a quick fix https://github.com/hlxsites/bevespi/pull/288
