### ISSUE TITLE
Global UI glitches (images, text)

### ISSUE THREAD

**Issue by dicagno** [hlxsites/bevespi#303]
<img width="466" alt="image" src="https://github.com/hlxsites/bevespi/assets/5924009/89fae340-d9da-47d4-aa48-1063b99fafa6">

Description: Image is cutting in landscape mode. Also please match the 
alignment of the About Copd text as per bevespi & design shape should be
there. – **This is global**
https://www.bevespi.com/about-copd/what-is-chronic-obstructive-pulmonary-disease.html
https://www.bevespi.com/about-copd/what-causes-copd.html
https://www.bevespi.com/about-copd/signs-and-symptoms-of-copd.html
https://www.bevespi.com/about-copd/copd-stages.html
https://www.bevespi.com/about-copd/copd-treatment.html

**Comment by paolomoz** [comment]
the image being cut in landscape mode should be considered an improvement, compared to image being shrinked in the original site (see screenshot of the original site below)

![IMG_8248](https://github.com/hlxsites/bevespi/assets/111385/95286859-d57f-4186-8f20-ade8dcadf54e)
