### ISSUE TITLE
/copd-management-resources UI glitches

### ISSUE THREAD

**Issue by dicagno** [hlxsites/bevespi#305]
![image](https://github.com/hlxsites/bevespi/assets/5924009/3c71482d-56cd-46c9-9646-f8c4c78c085e)

Description: Text colour getting changed in mobile

**Comment by paolomoz** [comment]
Cannot reproduce. Asking for more details about how to reproduce it.

**Comment by paolomoz** [comment]
Closing as not repro for now; will reopen based on customer feedback about reproducing it
