### ISSUE TITLE
Contact us fixes

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#373]
<img width="847" alt="Screenshot 2023-11-16 at 12 40 05" src="https://github.com/hlxsites/bevespi/assets/111385/25cb1c21-2bf0-49ce-bdcd-088e2aab6348">

**Comment by lansami** [comment]
Reopening the issue because point c is not fixed, reproducible only with an iphone

**Comment by lansami** [comment]
closed, issue fixed by https://github.com/hlxsites/bevespi/pull/378
