### ISSUE TITLE
Links decoration

### ISSUE THREAD

**Issue by hannessolo** [hlxsites/bevespi#49]
- [ ] Add new page icon to external links
- [ ] Add PDF icon to PDF links

![Screenshot 2023-10-16 at 10 53 10](https://github.com/hlxsites/bevespi/assets/24207564/67613f39-c584-40ec-b208-8e40a4ea4a2b)

https://www.bevespi.com/copd-management-resources.html

**Comment by paolomoz** [comment]
@hannessolo note that this is part of the fragment we have on each page (the same) https://github.com/hlxsites/bevespi/issues/8

**Comment by lansami** [comment]
in the fragment Important Safety Informations the images for the PDF links are inserted in the document, should we add them from code for the PDF link?

**Comment by paolomoz** [comment]
closing unless we find a need
