### ISSUE TITLE
Document structure

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#7]
Create respective word docs for:

- [ ]  https://www.bevespi.com/ (home page)
- [ ]  https://www.bevespi.com/copd-management-resources.html
- [ ]  https://www.bevespi.com/copd-treatment.html
- [ ]  https://www.bevespi.com/copd-management-resources/talking-to-your-doctor.html
- [ ]  https://www.bevespi.com/about-copd/what-causes-copd.html
- [ ]  https://www.bevespi.com/copd-management-resources/finding-personal-motivation.html
- [ ]  https://www.bevespi.com/copd-management-resources/staying-active.html
- [ ]  https://www.bevespi.com/copd-management-resources/creating-a-routine.html
- [ ]  https://www.bevespi.com/copd-management-resources/types-of-inhalers.html
- [ ]  https://www.bevespi.com/about-copd/copd-treatment.html
- [ ]  https://www.bevespi.com/copd-management-resources/what-is-copd.html
- [ ]  https://www.bevespi.com/how-to-use-bevespi-inhaler.html
- [ ]  https://www.bevespi.com/bevespi-coupon.html
- [ ]  https://www.bevespi.com/about-copd/signs-and-symptoms-of-copd.html
- [ ]  https://www.bevespi.com/about-copd/what-is-chronic-obstructive-pulmonary-disease.html
- [ ]  https://www.bevespi.com/copd-management-resources/getting-started-on-bevespi.html
- [ ]  https://www.bevespi.com/frequently-asked-questions.html
- [ ]  https://www.bevespi.com/copd-management-resources/shortness-of-breath.html
- [ ]  https://www.bevespi.com/about-copd/copd-stages.html
- [ ]  https://www.bevespi.com/copd-management-resources/activities-with-copd.html
- [x]  https://www.bevespi.com/contact-us.html
- [ ]  https://www.bevespi.com/bevespi-side-effects.html

**Comment by paolomoz** [comment]
@dicagno sorry for keeping this empty. My idea was to track status of content structure in Sharepoint, aka translating website content in word doc content. This was meant to be for all pages, maybe we need separate issues or a task list.
AFAICS index is not complete btw

**Comment by dicagno** [comment]
@paolomoz i can take care of creating a tasklists for that

**Comment by paolomoz** [comment]
@dicagno the full list of pages is here https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B4D0BB77B-A16E-417C-9C89-A09AFC1A9BAD%7D&file=pages.xlsx&action=default&mobileredirect=true

**Comment by dicagno** [comment]
as agreed with @lansami , he is taking over the content migration/creation task

**Comment by dicagno** [comment]
Superseded by #50
