### ISSUE TITLE
ISI Sticky: total height must be 142px

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#78]
From: https://issue-14-accordion--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler

<img width="1436" alt="Screenshot 2023-10-19 at 09 13 27" src="https://github.com/hlxsites/bevespi/assets/111385/206a3b0f-0210-4a48-a411-95e0948f5b3f">

**Comment by lansami** [comment]
Issue not reproducible on main, branch `issue-14-accordion` was merged in main
